In [1]:
import numpy as np

## 모듈과 클래스에 동시로 가지는 함수와 메소드 그리고 속성을 확인

In [2]:

s = set(dir(np))
n = set(dir(np.ndarray))
sn = s & n
count = 0
for i in sn :
    print(i, end=" ")
    count +=1
    if count % 5 == 0 :
        print()

all min conj resize argmin 
mean imag reshape ravel compress 
copy round diagonal nbytes searchsorted 
cumprod ptp nonzero partition std 
size __doc__ ndim dtype argmax 
conjugate argpartition cumsum max squeeze 
argsort swapaxes var sum clip 
trace repeat put take choose 
prod transpose any real dot 
shape sort 

In [3]:
a = np.array([1,2,3])

## 최대값과 최소값 구하기

In [16]:
np.min(a), np.max(a)

(1, 3)

In [17]:
np.argmin(a), np.argmax(a)

(0, 2)

In [18]:
a.min(), a.max()

(1, 3)

In [19]:
a.argmin(), a.argmax()

(0, 2)

## 논리 연산

In [4]:
np.all(a)

True

In [5]:
a.all()

True

In [20]:
np.any(a)

True

In [21]:
a.any()

True

# 합산과 평균, 분산, 표준편차

In [6]:
np.sum(a)

6

In [27]:
np.cumsum(a)

array([1, 3, 6])

In [7]:
a.sum()

6

In [28]:
a.cumsum()

array([1, 3, 6])

In [9]:
np.mean(a)

2.0

In [10]:
a.mean()

2.0

In [11]:
np.var(a)

0.66666666666666663

In [12]:
a.var()

0.66666666666666663

In [13]:
np.std(a)

0.81649658092772603

In [14]:
a.std()

0.81649658092772603

## 곱에 대한 연산.

In [22]:
np.prod(a)

6

In [23]:
np.cumprod(a)

array([1, 2, 6])

In [24]:
a.prod()

6

In [26]:
a.cumprod()

array([1, 2, 6])

## 실제 모양과 사이즈를 바꾸기

In [30]:
b = np.array([1,2,3,4,5,6])

In [44]:
b.ndim

1

In [43]:
b.size

6

In [34]:
c = np.resize(b,(2,3))

In [35]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
c.shape

(2, 3)

In [33]:
b.shape

(6,)

In [39]:
d = np.reshape(b,(2,3))

In [40]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
d.shape

(2, 3)

## 차원에 대한 변경도 표시할 수 있다.

In [45]:
a=np.array([[0,1],[2,3]])
ad = np.resize(a,(1,4))
print(ad)

[[0 1 2 3]]


In [46]:
ad = np.resize(a,(4,))
print(ad)

[0 1 2 3]


In [ ]:
conj  
imag ravel compress 
copy round diagonal nbytes searchsorted 
ptp nonzero partition 
dtype  
conjugate argpartition  squeeze 
argsort swapaxes  clip 
trace repeat put take choose 
transpose real dot 
shape sort 